import React, { useState } from 'react';
import { useStore } from '../context/StoreContext';
import { Product } from '../types';
import { X, Plus, PackagePlus, Check, Sparkles, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export const AddProductModal: React.FC = () => {
  const { isAddProductModalOpen, setIsAddProductModalOpen, addProduct, addToast } = useStore();

  const [title, setTitle] = useState('');
  const [subtitle, setSubtitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState<Product['category']>('Electronics');
  const [price, setPrice] = useState('89.00');
  const [compareAtPrice, setCompareAtPrice] = useState('119.00');
  const [costPrice, setCostPrice] = useState('35.00');
  const [inventory, setInventory] = useState('25');
  const [imageUrl, setImageUrl] = useState('https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&auto=format&fit=crop&q=80');
  const [badge, setBadge] = useState('In-House Stock');
  const [tags, setTags] = useState('Custom, Handcrafted, Premium');
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);

  const handleAIEnhance = async () => {
    if (!title.trim()) {
      addToast({
        title: 'Title Required',
        description: 'Please type a product title first so AI can craft descriptions for it.',
        type: 'warning'
      });
      return;
    }

    setIsGeneratingAI(true);
    try {
      const res = await fetch('/api/gemini/enhance-product', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title,
          category,
          currentDescription: description
        })
      });
      const data = await res.json();
      if (data.enhanced) {
        setDescription(data.enhanced);
        if (data.subtitle && !subtitle) setSubtitle(data.subtitle);
        if (data.tags && data.tags.length > 0) setTags(data.tags.join(', '));
        addToast({
          title: 'AI Copy Generated',
          description: 'Optimized product copywriting and tags generated by Gemini AI.',
          type: 'success'
        });
      }
    } catch (err) {
      console.error('AI enhance error:', err);
      addToast({
        title: 'AI Service Notice',
        description: 'Unable to reach AI enhancement endpoint.',
        type: 'warning'
      });
    } finally {
      setIsGeneratingAI(false);
    }
  };

  if (!isAddProductModalOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    addProduct({
      title: title.trim(),
      subtitle: subtitle.trim() || undefined,
      description: description.trim() || 'Premium precision-crafted item designed for performance and durability.',
      category,
      images: [imageUrl],
      price: parseFloat(price) || 99.00,
      compareAtPrice: compareAtPrice ? parseFloat(compareAtPrice) : null,
      costPrice: costPrice ? parseFloat(costPrice) : 30.00,
      inventory: parseInt(inventory, 10) || 10,
      status: 'published',
      isDropshipped: false,
      rating: 5.0,
      reviewCount: 1,
      badge: badge.trim() || undefined,
      tags: tags.split(',').map((t) => t.trim()).filter(Boolean),
      variants: [
        { id: 'v1', name: 'Standard Edition', priceOffset: 0, stock: parseInt(inventory, 10) || 10 }
      ]
    });

    setIsAddProductModalOpen(false);
  };

  return (
    <AnimatePresence>
      <div id="add-product-modal-overlay" className="fixed inset-0 z-50 overflow-y-auto bg-black/80 backdrop-blur-md flex items-center justify-center p-4 sm:p-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          transition={{ duration: 0.25 }}
          className="relative w-full max-w-2xl rounded-3xl bg-[#0f1420] border border-slate-800 shadow-2xl overflow-hidden my-8"
        >
          <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/80">
            <div className="flex items-center gap-2">
              <PackagePlus className="w-5 h-5 text-amber-400" />
              <h3 className="font-display font-bold text-base text-white">Create Custom In-House Product</h3>
            </div>
            <button
              onClick={() => setIsAddProductModalOpen(false)}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="p-6 space-y-4 max-h-[75vh] overflow-y-auto text-xs">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="sm:col-span-2">
                <label className="block font-semibold text-slate-300 mb-1">Product Title *</label>
                <input
                  type="text"
                  required
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Minimalist Titanium Precision Pen"
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-sm text-white focus:border-amber-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-300 mb-1">Subtitle / Tagline</label>
                <input
                  type="text"
                  value={subtitle}
                  onChange={(e) => setSubtitle(e.target.value)}
                  placeholder="e.g. Schmidt German Ink Refill with Bolt Action"
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-300 mb-1">Category</label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value as any)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                >
                  <option value="Electronics">Electronics</option>
                  <option value="Audio">Audio</option>
                  <option value="Wearables">Wearables</option>
                  <option value="Accessories">Accessories</option>
                  <option value="Home Office">Home Office</option>
                  <option value="Lifestyle">Lifestyle</option>
                </select>
              </div>

              <div className="sm:col-span-2">
                <div className="flex items-center justify-between mb-1">
                  <label className="block font-semibold text-slate-300">Description</label>
                  <button
                    id="add-product-ai-enhance-btn"
                    type="button"
                    disabled={isGeneratingAI}
                    onClick={handleAIEnhance}
                    className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-indigo-500/20 hover:bg-indigo-500/30 border border-indigo-500/30 text-indigo-300 text-[11px] font-semibold transition-all disabled:opacity-50"
                  >
                    {isGeneratingAI ? (
                      <>
                        <Loader2 className="w-3 h-3 animate-spin text-indigo-400" />
                        <span>Gemini AI Drafting...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-3 h-3 text-indigo-400" />
                        <span>AI Copywriter Assist</span>
                      </>
                    )}
                  </button>
                </div>
                <textarea
                  rows={3}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Detailed product story, craftsmanship, dimensions..."
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-300 mb-1">Retail Selling Price ($)</label>
                <input
                  type="number"
                  step="0.01"
                  value={price}
                  onChange={(e) => setPrice(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none font-bold"
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-300 mb-1">Compare-At Price ($)</label>
                <input
                  type="number"
                  step="0.01"
                  value={compareAtPrice}
                  onChange={(e) => setCompareAtPrice(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-300 mb-1">Internal Cost ($)</label>
                <input
                  type="number"
                  step="0.01"
                  value={costPrice}
                  onChange={(e) => setCostPrice(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-semibold text-slate-300 mb-1">Initial Stock Inventory</label>
                <input
                  type="number"
                  value={inventory}
                  onChange={(e) => setInventory(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                />
              </div>

              <div className="sm:col-span-2">
                <label className="block font-semibold text-slate-300 mb-1">Image URL (Unsplash or direct URL)</label>
                <input
                  type="url"
                  value={imageUrl}
                  onChange={(e) => setImageUrl(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3 py-2 text-white focus:border-amber-500 focus:outline-none"
                />
              </div>
            </div>

            <div className="pt-4 border-t border-slate-800 flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setIsAddProductModalOpen(false)}
                className="px-4 py-2 rounded-xl text-slate-400 hover:text-white"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 text-black font-bold text-xs hover:brightness-110 shadow-lg shadow-amber-500/20 flex items-center gap-1.5"
              >
                <Check className="w-4 h-4" />
                Publish Item to Store
              </button>
            </div>
          </form>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
